src/Form/CommentType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user')
            ->add('comment')
        ;
    }

    public function getName()
    {
        return 'blog_comment_type';
    }
}

templates/Page/about.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/about.html.twig #}
{% extends 'layout.html.twig' %}
{% block title %}{% trans %}blog.about{% endtrans %}{% endblock%}


{% block body %}
    <header>
        <h1>{% trans %}blog.about{% endtrans %} symblog</h1>
    </header>
    <article>
        <p>Donec imperdiet ante sed diam consequat et dictum erat faucibus. Aliquam sit
            amet vehicula leo. Morbi urna dui, tempor ac posuere et, rutrum at dui.
            Curabitur neque quam, ultricies ut imperdiet id, ornare varius arcu. Ut congue
            urna sit amet tellus malesuada nec elementum risus molestie. Donec gravida
            tellus sed tortor adipiscing fringilla. Donec nulla mauris, mollis egestas
            condimentum laoreet, lacinia vel lorem. Morbi vitae justo sit amet felis
            vehicula commodo a placerat lacus. Mauris at est elit, nec vehicula urna. Duis a
            lacus nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
            posuere cubilia Curae.</p>
    </article>
{% endblock %}

templates/Page/contact.html.twig
{# src/Blogger/BlogBundle/Resources/views/Page/contact.html.twig #}
{% extends 'layout.html.twig' %}
{% block title %}{% trans %}blog.contact{% endtrans %}{% endblock%}

{% block body %}
    <header>
        <h1>{% trans %}blog.contact{% endtrans %} symblog</h1>
    </header>


    {% for flashMessage in app.session.flashbag.get('blogger-notice') %}
        <div class="blogger-notice">
            {{ flashMessage }}
        </div>
    {% endfor %}


    <p>{% trans %}blog.contact.title{% endtrans %}</p>

    {{ form_start(form) }}

    {{ form_errors(form) }}

    {{ form_row(form.name) }}
    {{ form_row(form.email) }}
    {{ form_row(form.subject) }}
    {{ form_row(form.body) }}

    <div class="g-recaptcha" data-sitekey= {{ recaptcha_sitekey }}></div>

    <input type="submit" value="Submit" />

    {{ form_end(form) }}

{% endblock %}

templates/Page/contactEmail.txt.twig
{# src/Blogger/BlogBundle/Resources/views/Page/contactEmail.txt.twig #}
A contact enquiry was made by {{ enquiry.name }} at {{ "now" | date("Y-m-d H:i") }}.
Reply-To: {{ enquiry.email }}
Subject: {{ enquiry.subject }}
Body:
{{ enquiry.body }}

templates/Page/index.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
    {% for article in my_pager.currentPageResults %}
        {% set blog_path = path('blog_show', { 'slug': article.slug })  %}
        <article class="blog">
            <div class="date"><time datetime="{{ article.created|date('c') }}">{{ article.created|date('l, F j, Y') }}</time></div>
            <header>
                <h2><a href="{{ blog_path }}">{{ article.title }}</a></h2>
            </header>

            <img src="{{ asset(['images/', article.image]|join) }}" />
            <div class="snippet">
                <p>{{ article.body(500) }}</p>
                <p class="continue"><a href="{{ blog_path }}">{% trans %}blog.continue.reading{% endtrans %}</a></p>
            </div>

            <footer class="meta">
                <p>{% trans %}blog.comments: {% endtrans %}  <a href="{{ blog_path }}#comments">{{ article.comments|length }}</a></p>
                <p>{% trans %}blog.posted.by{% endtrans %} <span class="highlight">{{ article.author }}</span> at {{ article.created|date('h:iA') }}</p>
                <p>{% trans %}blog.tags: {% endtrans %} <span class="highlight">{{ article.tags }}</span></p>
            </footer>
        </article>
    {% else %}
        <p>{% trans %}blog.no.articles{% endtrans %} </p>
    {% endfor %}
    <div class="pagerfanta">
        {{ pagerfanta(my_pager) }}
    </div>
{% endblock %}

templates/Page/sidebar.html.twig
<section class="section">
    <header>
        <h3>{% trans %}blog.categories{% endtrans %} </h3>
    </header>
    <p class="tags">
        {% for category in categories %}
        <a href="{{ path('blog_category_show', { 'category':  category}) }}">
            {{ category }}
        </a>
        {% else %}
    <p>{% trans %}blog.no.categories{% endtrans %} </p>
    {% endfor %}
    </p>
</section>
<section class="section">
    <header>
        <h3>{% trans %}blog.tag.cloud{% endtrans %} </h3>
    </header>
    <p class="tags">
        {% for tag, weight in tags %}
        <span class="weight-{{ weight }}">{{ tag }}</span>
        {% else %}
    <p>{% trans %}blog.no.tags{% endtrans %} </p>
    {% endfor %}
    </p>
</section>
<section class="section">
    <header>
        <h3>{% trans %}blog.latest.comments{% endtrans %} </h3>
    </header>
    {% for comment in latestComments %}
        <article class="comment">
            <header>
                <p class="small"><span class="highlight">{{ comment.user }}</span>
                    {% trans %}blog.commented.on{% endtrans %}
                    <a href="{{ path('blog_show', { 'id': comment.article.id, 'slug': comment.article.slug }) }}#comment-{{ comment.id }}">
                            {{ comment.article.title }}
                    </a>
                    <em><time datetime="{{ comment.created|date('c') }}">{{ comment.created|created_ago }}</time></em>
                </p>
            </header>
            <p>{{ comment.comment }}</p>
            </p>
        </article>
    {% else %}
        <p>There are no recent comments {% trans %}blog.no.comments{% endtrans %}
        </p>
    {% endfor %}
</section>